# Twig Configuration
twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        app_title: '%env(APP_TITLE)%'
        app_url: '%env(APP_URL)%'