easy_admin:
  design:
    menu:
      - label: 'Dashboard'
        role: ROLE_USER
        icon: 'dashboard'
        route: admin_dashboard
        default: true

      - label: 'Taches'
        role: ROLE_USER
        icon: 'dashboard'
        entity: 'Task'

      - label: 'Activites'
        role: ROLE_USER
        icon: 'dashboard'
        entity: 'Activity'

      - label: 'Jobs'
        role: ROLE_USER
        icon: 'dashboard'
        entity: 'Job'

      - label: 'Temps de travail'
        role: ROLE_USER
        icon: 'dashboard'
        entity: 'WorkingTime'

      - label: 'Projets'
        role: ROLE_USER
        icon: 'dashboard'
        entity: 'Project'

      - label: 'Utilisateurs'
        role: ROLE_ADMIN
        icon: 'users'
        children:
          - label: entity.user.title
            entity: 'User'
            icon: 'user'
          - label: entity.admin.title
            entity: 'Admin'
            icon: 'user-circle-o'