easy_admin:
  design:
    menu:
      - label: 'Dashboard'
        role: ROLE_USER
        icon: 'dashboard'
        route: admin_dashboard
        default: true

      - label: 'Taches'
        role: ROLE_USER
        icon: 'dashboard'
        children:
          - label: entity.task.title
            entity: 'Task'
          - label: entity.taskno.title
            entity: 'NotValidateTask'

      - label: 'Activités'
        role: ROLE_USER
        icon: 'dashboard'
        children:
          - label: entity.activity.title
            entity: 'Activity'
          - label: entity.activityno.title
            entity: 'NotValidateActivity'

      - label: 'Métiers'
        role: ROLE_USER
        icon: 'dashboard'
        children:
          - label: entity.job.title
            entity: 'Job'
          - label: entity.jobno.title
            entity: 'NotValidateJob'

      - label: 'Temps de travail'
        role: ROLE_USER
        icon: 'dashboard'
        children:
          - label: entity.workingtime.title
            entity: 'WorkingTime'
          - label: entity.workingtimeno.title
            entity: 'NotValidateWorkingTime'

      - label: 'Projets'
        role: ROLE_USER
        icon: 'dashboard'
        children:
          - label: entity.project.title
            entity: 'Project'
          - label: entity.projectno.title
            entity: 'NotValidateProject'

      - label: 'Utilisateurs'
        role: ROLE_ADMIN
        icon: 'users'
        children:
          - label: entity.user.title
            entity: 'User'
            icon: 'user'
          - label: entity.admin.title
            entity: 'Admin'
            icon: 'user-circle-o'