easy_admin:
    entities:

        Job:
            label: entity.job.label
            class: App\Entity\Job
            role: ROLE_ADMIN
            list:
                title: entity.job.list
                dql_filter: "entity.isValidate = 1"
                fields:
                    - { property: name, label: entity.job.name }
            form:
                fields:
                    - { property: name, label: entity.job.name }
            disabled_actions: ['delete']

        NotValidateJob:
            label: entity.job.label
            class: App\Entity\Job
            new:
                role: ROLE_SUPER_ADMIN
            role: ROLE_ADMIN
            list:
                title: entity.job.list
                dql_filter: "entity.isValidate = 0"
                fields:
                    - { property: name, label: entity.job.name }
            form:
                fields:
                    - { property: name, label: entity.job.name }
            disabled_actions: ['delete', 'new']
