easy_admin:
    entities:

        Project:
            label: entity.project.label
            class: App\Entity\Project
            role: ROLE_ADMIN
            list:
                title: entity.project.list
                dql_filter: "entity.isValidate = 1"
                fields:
                    - { property: name,  label: entity.project.name }
                    - { property: description, label: entity.project.description }
                    - { property: company, label: entity.project.company }
                    - { property: created_at, label: entity.project.created_at }
                    - { property: relevantSite, label: entity.project.relevantSite }
                    - { property: asPartOfPulpit,  type: 'boolean', label: entity.project.asPartOfPulpit }
                    - { property: deadline, label: entity.project.deadline }

            form:
                fields:
                    - { property: name, label: entity.project.name }
                    - { property: description, label: entity.project.description }
                    - { property: company, label: entity.project.company }
                    - { property: created_at, label: entity.project.created_at }
                    - { property: claimantName, label: entity.project.claimantName }
                    - { property: job, label: entity.project.job }
                    - { property: relevantSite, label: entity.project.relevantSite }
                    - { property: asPartOfPulpit, label: entity.project.asPartOfPulpit }
                    - { property: isValidate, label: entity.project.isValidate }
                    - { property: deadline, label: entity.project.deadline }
                    - { property: documents, label: entity.project.documents }
                    - { property: activityType, label: entity.project.activityType }
            disabled_actions: ['delete']

        NotValidateProject:
            label: entity.project.label
            class: App\Entity\Project
            new:
                role: ROLE_SUPER_ADMIN
            role: ROLE_ADMIN
            list:
                title: entity.project.list
                dql_filter: "entity.isValidate = 0"
                fields:
                    - { property: name,  label: entity.project.name }
                    - { property: description, label: entity.project.description }
                    - { property: company, label: entity.project.company }
                    - { property: created_at, label: entity.project.created_at }
                    - { property: relevantSite, label: entity.project.relevantSite }
                    - { property: asPartOfPulpit,  type: 'boolean', label: entity.project.asPartOfPulpit }
                    - { property: deadline, label: entity.project.deadline }

            form:
                fields:
                    - { property: name, label: entity.project.name }
                    - { property: description, label: entity.project.description }
                    - { property: company, label: entity.project.company }
                    - { property: created_at, label: entity.project.created_at }
                    - { property: claimantName, label: entity.project.claimantName }
                    - { property: job, label: entity.project.job }
                    - { property: relevantSite, label: entity.project.relevantSite }
                    - { property: asPartOfPulpit, label: entity.project.asPartOfPulpit }
                    - { property: isValidate, label: entity.project.isValidate }
                    - { property: deadline, label: entity.project.deadline }
                    - { property: documents, label: entity.project.documents }
                    - { property: activityType, label: entity.project.activityType }
            disabled_actions: ['delete', 'new']