easy_admin:
    entities:

        Task:
            label: entity.task.label
            class: App\Entity\Task
            role: ROLE_ADMIN
            list:
                title: entity.task.list
                dql_filter: "entity.isValidate = 1"
                fields:
                    - { property: activity.name, label: entity.activity.name }
                    - { property: name, label: entity.task.name }
                    - { property: defaultTime, label: entity.task.defaultTime }
                    - { property: isValidate, type: 'boolean', label: entity.task.isValidate}
            form:
                fields:
                    - { property: activity, label: entity.activity.name }
                    - { property: name, label: entity.task.name }
                    - { property: defaultTime, label: entity.task.defaultTime }

            disabled_actions: ['delete']

        NotValidateTask:
            label: entity.taskno.label
            class: App\Entity\Task
            new:
                role: ROLE_SUPER_ADMIN
            role: ROLE_ADMIN
            list:
                title: entity.taskno.list
                dql_filter: "entity.isValidate = 0"
                fields:
                    - { property: activity.name, label: entity.activity.name }
                    - { property: name, label: entity.task.name }
                    - { property: defaultTime, label: entity.task.defaultTime }
                    - { property: isValidate, type: 'boolean', label: entity.task.isValidate}
            form:
                fields:
                    - { property: activity, label: entity.activity.name }
                    - { property: name, label: entity.task.name }
                    - { property: defaultTime, label: entity.task.defaultTime }

            disabled_actions: ['delete', 'new']