easy_admin:
    entities:

        Task:
            label: entity.task.label
            class: App\Entity\Task
            role: ROLE_ADMIN
            list:
                title: entity.task.list
                fields:
                    - { property: activity.name, label: entity.activity.name }
                    - { property: name, label: entity.task.name }
                    - { property: defaultTime, label: entity.task.defaultTime }
            form:
                fields:
                    - { property: activity, label: entity.activity.name }
                    - { property: name, label: entity.task.name }
                    - { property: defaultTime, label: entity.task.defaultTime }