easy_admin:
    entities:

        User:
            label: entity.user.label
            class: App\Entity\User
            role: ROLE_ADMIN
            list:
                title: entity.user.list
                dql_filter: "entity.roles NOT LIKE '%%ROLE_ADMIN%%' AND entity.roles NOT LIKE '%%ROLE_SUPER_ADMIN%%'"
                fields:
                    - { property: email, label: entity.user.email }
            form:
                fields:
                    - { property: smartphoneId, label: entity.user.smartphoneId }
                    - { property: firstname, label: entity.user.firstname }
                    - { property: lastname, label: entity.user.lastname }
                    - { property: email, label: entity.user.email }
                    - { property: isEligible, label: entity.user.isEligible }
            edit:
                fields:
                - '-plainPassword'

        Admin:
            label: entity.admin.label
            class: App\Entity\User
            role: ROLE_SUPER_ADMIN
            list:
                title: entity.admin.list
                dql_filter: "entity.roles LIKE '%%ROLE_ADMIN%%' OR entity.roles LIKE '%%ROLE_SUPER_ADMIN%%'"
                fields:
                    - { property: email, label: entity.user.email }
            form:
                fields:
                    - { property: plainPassword, label: entity.user.plainPassword, type: 'text', type_options: { required: true } }
                    - { property: email, label: entity.user.email }
            edit:
              fields:
              - '-plainPassword'
            export:
                fields:
                    - { property: username, label: entity.user.username }
                    - { property: email, label: entity.user.email }
                    - { property: enabled, label: entity.user.enabled }