# REQUIRED :
#   name : Entity name
#   showAll : Word in url to show one record of entity
#   showOne : Word in url to show all records of entity
# OPTIONAL :
#   showAllFields : Fields to show
#   showAllCondition : Fields to filter
#   showOneBy : Field to filter

api:
  entities:
    - { name: User, showAll: user, showOne: user }
    - { name: Activity, showAll: activity, showOne: activity }
    - { name: Job, showAll: job, showOne: job }
    - { name: Project, showAll: project, showAllCondition: 'project.isValidate = 1 and project.isEligibleCIR = 1', showOne: project }
    - { name: Task, showAll: task, showOne: task }
    - { name: Settings, showAll: setting, showOne: settings }
    - { name: WorkingTime, showAll: working_time, showOne: working_time }