# REQUIRED :
#   name : Entity name
#   showAll : Word in url to show one record of entity
#   showOne : Word in url to show all records of entity
# OPTIONAL :
#   showAllFields : Fields to show
#   showAllCondition : Fields to filter
#   showOneBy : Field to filter

api:
  entities:
    - { name: User, showAll: user, showAllCondition: 'user.enabled = 1 and user.isEligible = 1', showOne: user }
    - { name: Activity, showAll: activity, showAllCondition: 'activity.isValidate = 1', showOne: activity }
    - { name: Job, showAll: job, showAllCondition: 'job.isValidate = 1', showOne: job }
    - { name: Project, showAll: project, showAllCondition: 'project.isValidate = 1 and project.isEligibleCIR = 1', showOne: project }
    - { name: Task, showAll: task, showAllCondition: 'task.isValidate = 1', showOne: task }
    - { name: Settings, showAll: setting, showOne: settings }
    - { name: WorkingTime, showAll: working_time, showAllCondition: 'working_time.isValidate = 1', showOne: working_time }